---
abstract: 'We are Canadian CPAN authors'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Canadian
provides:
  Acme::CPANAuthors::Canadian:
    file: lib/Acme/CPANAuthors/Canadian.pm
    version: 0.0103
requires:
  Acme::CPANAuthors: 0.06
  Acme::CPANAuthors::Register: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
