---
name: Acme-CPANAuthors-Canadian
version: 0.0102
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: We are Canadian CPAN authors
license: perl
build_requires:
  Test::More: 0
requires:
  Acme::CPANAuthors: 0.06
  Acme::CPANAuthors::Register: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Acme::CPANAuthors::Canadian:
    file: lib/Acme/CPANAuthors/Canadian.pm
    version: 0.0102
resources:
  license: http://dev.perl.org/licenses/
