---
abstract: 'We are Canadian CPAN authors'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Canadian
requires:
  Acme::CPANAuthors: 0.06
  Acme::CPANAuthors::Register: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/zoffixznet/Acme-CPANAuthors-Canadian/issues
  repository: git://github.com/zoffixznet/Acme-CPANAuthors-Canadian.git
version: 0.0106
